### ISSUE TITLE
Consider a license

### ISSUE THREAD

**Issue by J3RN** [TanklesXL/aoc_template#1]
Hello! :wave: Thanks for creating this project! I've enjoyed looking over your code.

I'm starting to work on a file i/o module for the Gleam stdlib, and would love to use your file i/o code as a reference. However, without a license, your code is "all rights reserved."

If you're interested in adding a license, there are [several to choose from](https://choosealicense.com/licenses/)! Gleam itself uses the Apache 2.0 License, as does Elixir and Erlang/OTP. For your project, though, the choice is yours!

In any event, love the project! Happy hacking!

**Comment by TanklesXL** [comment]
:wave: Thanks for bringing this to my attention! I'll likely follow whatever Gleam is using so I guess Apache 2.0 it is!
